const users = [
  {
    id: '1',
    name: 'Neal Balistreri',
    email: 'karelle.murazik@gmail.com',
    department: '1',
    role: 'Head of Engineering',
    active: false,
    joined_at: '2023-11-03',
  },
  {
    id: '2',
    name: 'Rufus Pfannerstill',
    email: 'casper70@yahoo.com',
    department: '1',
    role: 'QA Engineer',
    active: true,
    joined_at: '2024-04-08',
  },
  {
    id: '3',
    name: 'Dan Lemke',
    email: 'reba98@hotmail.com',
    department: '1',
    role: 'Backend Developer',
    active: true,
    joined_at: '2023-01-29',
  },
  {
    id: '4',
    name: 'Ms. Paula Hoeger',
    email: 'angelita.heathcote8@hotmail.com',
    department: '1',
    role: 'Senior Developer',
    active: true,
    joined_at: '2024-01-13',
  },
  {
    id: '5',
    name: 'Jeremiah Watsica',
    email: 'mortimer_ward@yahoo.com',
    department: '1',
    role: 'Frontend Developer',
    active: true,
    joined_at: '2023-07-31',
  },
  {
    id: '6',
    name: 'Marvin Collins',
    email: 'emmy_okon@gmail.com',
    department: '1',
    role: 'Frontend Developer',
    active: true,
    joined_at: '2025-04-09',
  },
  {
    id: '7',
    name: 'Adrian Stiedemann Sr.',
    email: 'maegan44@hotmail.com',
    department: '1',
    role: 'DevOps Engineer',
    active: true,
    joined_at: '2023-09-11',
  },
  {
    id: '8',
    name: 'Eunice Powlowski',
    email: 'damien_hessel65@yahoo.com',
    department: '1',
    role: 'Backend Developer',
    active: true,
    joined_at: '2024-06-29',
  },
  {
    id: '9',
    name: 'Jill Gutkowski',
    email: 'myriam35@hotmail.com',
    department: '1',
    role: 'Backend Developer',
    active: true,
    joined_at: '2025-04-20',
  },
  {
    id: '10',
    name: 'Cecelia Koss Sr.',
    email: 'lonny22@hotmail.com',
    department: '1',
    role: 'QA Engineer',
    active: true,
    joined_at: '2023-02-20',
  },
  {
    id: '11',
    name: 'Christian Deckow',
    email: 'lauriane_thompson@gmail.com',
    department: '1',
    role: 'Senior Developer',
    active: true,
    joined_at: '2024-06-30',
  },
  {
    id: '12',
    name: 'Opal Klocko MD',
    email: 'murphy_watsica@gmail.com',
    department: '1',
    role: 'QA Engineer',
    active: true,
    joined_at: '2023-02-18',
  },
  {
    id: '13',
    name: 'Paulette Crona',
    email: 'jarrett19@yahoo.com',
    department: '1',
    role: 'Tech Lead',
    active: true,
    joined_at: '2023-11-24',
  },
  {
    id: '14',
    name: "Noah O'Conner",
    email: 'wendy.crona9@yahoo.com',
    department: '1',
    role: 'Backend Developer',
    active: true,
    joined_at: '2024-03-13',
  },
  {
    id: '15',
    name: 'Dr. Donnie Hackett',
    email: 'lorenz20@hotmail.com',
    department: '1',
    role: 'Senior Developer',
    active: true,
    joined_at: '2024-05-17',
  },
  {
    id: '16',
    name: 'Ricardo Metz',
    email: 'cecelia.schulist@gmail.com',
    department: '1',
    role: 'Frontend Developer',
    active: true,
    joined_at: '2024-03-31',
  },
  {
    id: '17',
    name: "Al O'Connell",
    email: 'augusta_batz@gmail.com',
    department: '1',
    role: 'Frontend Developer',
    active: true,
    joined_at: '2023-11-24',
  },
  {
    id: '18',
    name: 'Melissa Emard',
    email: 'jaeden.mcclure75@hotmail.com',
    department: '1',
    role: 'Backend Developer',
    active: true,
    joined_at: '2025-04-20',
  },
  {
    id: '19',
    name: 'Mindy McClure',
    email: 'nigel1@hotmail.com',
    department: '1',
    role: 'Backend Developer',
    active: true,
    joined_at: '2023-08-10',
  },
  {
    id: '20',
    name: 'Sheldon Beatty',
    email: 'chadd26@gmail.com',
    department: '1',
    role: 'Frontend Developer',
    active: true,
    joined_at: '2025-02-27',
  },
  {
    id: '21',
    name: 'Dr. Kim Kreiger',
    email: 'gilbert40@yahoo.com',
    department: '1',
    role: 'Tech Lead',
    active: true,
    joined_at: '2024-12-28',
  },
  {
    id: '22',
    name: 'Pablo Fisher-Schuppe',
    email: 'avis32@hotmail.com',
    department: '1',
    role: 'Tech Lead',
    active: true,
    joined_at: '2024-08-15',
  },
  {
    id: '23',
    name: 'Billy Kiehn',
    email: 'arvid81@hotmail.com',
    department: '1',
    role: 'DevOps Engineer',
    active: true,
    joined_at: '2025-01-23',
  },
  {
    id: '24',
    name: 'Rachael Herzog',
    email: 'arno.hirthe58@yahoo.com',
    department: '1',
    role: 'DevOps Engineer',
    active: true,
    joined_at: '2025-02-26',
  },
  {
    id: '25',
    name: 'Dallas Russel',
    email: 'roy_oconner-crooks@yahoo.com',
    department: '1',
    role: 'Tech Lead',
    active: true,
    joined_at: '2023-10-02',
  },
  {
    id: '26',
    name: 'Dr. Gerardo Murphy',
    email: 'mia_mante-ratke@yahoo.com',
    department: '2',
    role: 'Head of Design',
    active: true,
    joined_at: '2023-09-19',
  },
  {
    id: '27',
    name: 'Carrie Marvin',
    email: 'amiya.koch95@gmail.com',
    department: '2',
    role: 'Design Lead',
    active: true,
    joined_at: '2024-04-08',
  },
  {
    id: '28',
    name: 'Rosalie Ratke III',
    email: 'rashad_orn14@yahoo.com',
    department: '2',
    role: 'Visual Designer',
    active: true,
    joined_at: '2025-04-07',
  },
  {
    id: '29',
    name: 'Gretchen Dach',
    email: 'jed_hegmann@hotmail.com',
    department: '2',
    role: 'Product Designer',
    active: true,
    joined_at: '2025-06-27',
  },
  {
    id: '30',
    name: 'Florence Cummerata',
    email: 'evangeline.brown@hotmail.com',
    department: '2',
    role: 'Product Designer',
    active: true,
    joined_at: '2023-07-16',
  },
  {
    id: '31',
    name: 'Ray Durgan',
    email: 'faustino_herzog27@gmail.com',
    department: '2',
    role: 'UX Designer',
    active: true,
    joined_at: '2025-04-06',
  },
  {
    id: '32',
    name: 'Darnell Bayer',
    email: 'kariane44@hotmail.com',
    department: '2',
    role: 'UX Designer',
    active: true,
    joined_at: '2024-12-10',
  },
  {
    id: '33',
    name: 'Tony Welch',
    email: 'cynthia_greenholt31@gmail.com',
    department: '2',
    role: 'Visual Designer',
    active: true,
    joined_at: '2024-11-29',
  },
  {
    id: '34',
    name: 'Jasmine Pollich',
    email: 'demond.mohr@gmail.com',
    department: '3',
    role: 'Head of Marketing',
    active: true,
    joined_at: '2024-06-27',
  },
  {
    id: '35',
    name: 'Owen Barrows',
    email: 'hayley_cormier@hotmail.com',
    department: '3',
    role: 'Digital Marketer',
    active: true,
    joined_at: '2023-07-27',
  },
  {
    id: '36',
    name: 'Doreen Stroman',
    email: 'terrell.sipes@gmail.com',
    department: '3',
    role: 'Digital Marketer',
    active: true,
    joined_at: '2023-02-02',
  },
  {
    id: '37',
    name: 'Marco Ruecker',
    email: 'mariah49@yahoo.com',
    department: '3',
    role: 'Digital Marketer',
    active: true,
    joined_at: '2023-07-10',
  },
  {
    id: '38',
    name: 'Susie Halvorson',
    email: 'darby79@hotmail.com',
    department: '3',
    role: 'Digital Marketer',
    active: true,
    joined_at: '2024-06-29',
  },
  {
    id: '39',
    name: 'Marvin Tromp PhD',
    email: 'rahul.wilkinson2@hotmail.com',
    department: '3',
    role: 'Brand Manager',
    active: true,
    joined_at: '2024-02-23',
  },
  {
    id: '40',
    name: 'Naomi Ratke',
    email: 'julio38@hotmail.com',
    department: '4',
    role: 'Head of Operations',
    active: true,
    joined_at: '2023-11-23',
  },
  {
    id: '41',
    name: 'Kyle Jenkins',
    email: 'shannon51@hotmail.com',
    department: '4',
    role: 'Business Analyst',
    active: true,
    joined_at: '2023-09-04',
  },
  {
    id: '42',
    name: 'Patty Mueller',
    email: 'alvis79@gmail.com',
    department: '4',
    role: 'Business Analyst',
    active: true,
    joined_at: '2024-06-09',
  },
  {
    id: '43',
    name: 'Clayton Casper',
    email: 'alia.hoeger38@hotmail.com',
    department: '4',
    role: 'Process Specialist',
    active: true,
    joined_at: '2023-01-09',
  },
  {
    id: '44',
    name: 'Danielle Weimann',
    email: 'kaylee22@hotmail.com',
    department: '4',
    role: 'Business Analyst',
    active: true,
    joined_at: '2025-05-02',
  },
  {
    id: '45',
    name: 'Wanda Ebert-Miller',
    email: 'simone43@gmail.com',
    department: '4',
    role: 'Project Manager',
    active: true,
    joined_at: '2025-05-09',
  },
  {
    id: '46',
    name: 'Dr. Jan Becker',
    email: 'rosemarie.hills57@gmail.com',
    department: '4',
    role: 'Process Specialist',
    active: true,
    joined_at: '2024-05-15',
  },
  {
    id: '47',
    name: 'Jenna Bailey',
    email: 'philip81@yahoo.com',
    department: '4',
    role: 'Project Manager',
    active: true,
    joined_at: '2023-04-26',
  },
  {
    id: '48',
    name: 'Lindsay Macejkovic DDS',
    email: 'zella.bartell42@gmail.com',
    department: '4',
    role: 'Project Manager',
    active: true,
    joined_at: '2025-04-12',
  },
  {
    id: '49',
    name: 'Shane Rau',
    email: 'drake.ratke99@yahoo.com',
    department: '4',
    role: 'Operations Manager',
    active: true,
    joined_at: '2025-04-07',
  },
  {
    id: '50',
    name: 'Patsy Barrows-Tillman MD',
    email: 'ford.lowe76@yahoo.com',
    department: '4',
    role: 'Business Analyst',
    active: true,
    joined_at: '2023-07-05',
  },
  {
    id: 51,
    name: 'Mamie Marvin DVM',
    email: 'darrion44@hotmail.com',
    department: '4',
    role: 'Business Analyst',
    active: true,
    joined_at: '2024-10-29',
  },
  {
    id: 52,
    name: 'Herman Kemmer',
    email: 'reta.dooley25@hotmail.com',
    department: '5',
    role: 'Head of Communication',
    active: true,
    joined_at: '2023-09-04',
  },
  {
    id: 53,
    name: 'Jerry Dickinson',
    email: 'warren93@gmail.com',
    department: '5',
    role: 'Social Media Manager',
    active: true,
    joined_at: '2023-08-24',
  },
  {
    id: 54,
    name: 'Mr. Andre Kulas',
    email: 'dion97@yahoo.com',
    department: '5',
    role: 'Community Manager',
    active: true,
    joined_at: '2024-11-23',
  },
  {
    id: 55,
    name: 'Jerald Mann',
    email: 'junior.walter@yahoo.com',
    department: '5',
    role: 'Content Writer',
    active: true,
    joined_at: '2023-08-08',
  },
  {
    id: 56,
    name: 'Isabel Wintheiser',
    email: 'adolph_fritsch86@hotmail.com',
    department: '5',
    role: 'Social Media Manager',
    active: true,
    joined_at: '2023-10-13',
  },
  {
    id: 57,
    name: 'Edwin McCullough',
    email: 'hailee.botsford32@gmail.com',
    department: '5',
    role: 'PR Manager',
    active: true,
    joined_at: '2023-07-05',
  },
  {
    id: 58,
    name: 'Harriet Kunze Jr.',
    email: 'burley0@yahoo.com',
    department: '5',
    role: 'Communications Manager',
    active: true,
    joined_at: '2024-03-30',
  },
  {
    id: 59,
    name: 'Connie Macejkovic',
    email: 'elliott95@yahoo.com',
    department: '5',
    role: 'PR Manager',
    active: true,
    joined_at: '2024-04-10',
  },
  {
    id: 60,
    name: 'Cindy Senger',
    email: 'desmond_monahan@yahoo.com',
    department: '5',
    role: 'PR Manager',
    active: true,
    joined_at: '2023-07-02',
  },
  {
    id: 61,
    name: 'Dr. Cecilia Gleason',
    email: 'solon.gusikowski59@hotmail.com',
    department: '5',
    role: 'Community Manager',
    active: true,
    joined_at: '2024-02-06',
  },
  {
    id: 62,
    name: 'Kristine Kshlerin',
    email: 'murray_ondricka93@gmail.com',
    department: '5',
    role: 'Community Manager',
    active: true,
    joined_at: '2023-11-22',
  },
  {
    id: 63,
    name: 'Eugene Johns',
    email: 'maudie.yundt51@hotmail.com',
    department: '5',
    role: 'Content Writer',
    active: true,
    joined_at: '2023-12-12',
  },
  {
    id: 64,
    name: 'Yvette Heaney',
    email: 'lauretta_krajcik@yahoo.com',
    department: '5',
    role: 'Communications Manager',
    active: true,
    joined_at: '2023-05-19',
  },
  {
    id: 65,
    name: 'Lillie Homenick-Predovic',
    email: 'daphney_haag@gmail.com',
    department: '5',
    role: 'Social Media Manager',
    active: true,
    joined_at: '2024-10-11',
  },
  {
    id: 66,
    name: 'Marco Lehner',
    email: 'vernie_bahringer58@yahoo.com',
    department: '5',
    role: 'PR Manager',
    active: true,
    joined_at: '2024-04-11',
  },
];
