import type { Metadata } from "next";
import { Inter } from "next/font/google";
// @ts-expect-error: CSS import side effects are handled by Next.js
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import AppHeader from "@/components/layout/app-header";
import Footer from "@/components/footer";
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { QueryProvider } from "@/components/providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("font-sans", inter.variable)}
      suppressHydrationWarning
    >
      <body
        className={`antialiased bg-bg-layout text-foreground min-h-screen flex flex-col  py-0 ${inter.className}`}
      >
        <div className="app-bg min-h-screen">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <QueryProvider>
              <AppHeader />
              <TooltipProvider>
                <main className="flex-1 w-full px-10">{children}</main>
                <Toaster richColors position="top-right" />
              </TooltipProvider>
              <Footer />
            </QueryProvider>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
