export const toolsSeed = [
  {
    name: 'Slack',
    vendor: 'Slack Technologies',
    category: 'Communication',
    ownerDepartment: 'Communication',
    monthlyCost: 2632,
    websiteUrl: 'https://slack.com',
    description: 'Team messaging and collaboration platform',
    status: 'active',
    iconUrl: '',
    previousMonthCost: 0,
    activeUsersCount: 0,
  },
  {
    name: 'Figma',
    vendor: 'Figma Inc',
    category: 'Design',
    ownerDepartment: 'Engineering',
    monthlyCost: 534,
    websiteUrl: 'https://figma.com',
    description: 'Collaborative design and prototyping tool',
    status: 'active',
    iconUrl: 'https://static.figma.com/app/icon/1/favicon.png',
    previousMonthCost: 0,
    activeUsersCount: 0,
  },
];
